// <auto-generated />
using IEXTrading.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace IEXTrading.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200423002422_InitialCreate_1")]
    partial class InitialCreate_1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IEXTrading.Models.Rec", b =>
                {
                    b.Property<int>("aid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("activity");

                    b.Property<string>("address");

                    b.Property<string>("age_requirements");

                    b.Property<string>("days_of_week");

                    b.Property<string>("phone_number");

                    b.Property<string>("recreation_center");

                    b.Property<string>("times");

                    b.HasKey("aid");

                    b.ToTable("Rec_centers");
                });

            modelBuilder.Entity("IEXTrading.Models.Signup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("RecID");

                    b.Property<string>("activity");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<int>("aid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("days_of_week")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("first_name")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("last_name")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("recreation_center")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("times")
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
